name: p7zip-release

on:
  push:
    branches:
      - '**'

  pull_request:

  release:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    name: Linux-ARM64-Release
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            gcc \
            g++ \
            make \
            cmake

      - name: Build 7zz
        run: |
          mkdir -p linux-p7zip/bin
          mkdir -p linux-p7zip/lib

          export PROJECT_ROOT=$(pwd)

          cd CPP/7zip/Bundles/Alone2

          make -f makefile.gcc -j$(nproc)

          INSTALL_PREFIX=$PROJECT_ROOT/linux-p7zip \
          make -f makefile.gcc install

      - name: Check binary
        run: |
          export PROJECT_ROOT=$(pwd)

          git clone https://github.com/jinfeihan57/p7zip_test_utils.git

          cd p7zip_test_utils/check

          bash check.sh $PROJECT_ROOT/linux-p7zip/bin/7zz

      - name: Build 7z.so
        run: |
          export PROJECT_ROOT=$(pwd)

          cd CPP/7zip/Bundles/Format7zF

          make -f makefile.gcc -j$(nproc)

          INSTALL_PREFIX=$PROJECT_ROOT/linux-p7zip \
          make -f makefile.gcc install

      - name: Package
        run: |
          ./linux-p7zip/bin/7zz a linux-p7zip-linux-arm64.7z linux-p7zip -y
          ./linux-p7zip/bin/7zz a linux-p7zip-linux-arm64.zip linux-p7zip -y

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-p7zip-linux-arm64
          path: |
            linux-p7zip-linux-arm64.7z
            linux-p7zip-linux-arm64.zip

      - name: Upload release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux-p7zip-linux-arm64.*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Linux ARM64 p7zip release"
